
{
  "model": {
    "regression": False,
    "model_name": "pointnet",
    "model_kwargs": {
      "input_size": 3,
      "num_classes": 8,
      "transform_scale": 0.001,
    },
    "learning_rate": 0.0001,
  },
  "data": {
    "batch_size": 16,
    "num_workers": 0,
    "ratio_validation": 0.2,
    "normalize": True,
  },
  "trainer": {
    "max_epochs": 200,
    "log_every_n_steps": 1,
  },
  "debug": True,
}